const router = require("express").Router();
const UserRouter = require("./UserRoute/UserRouter");
const JobRouter = require("./JobRoute/JobRoute");
const CategoryRouter = require("./CategoryRoute/CategoryRoute");
const Sub_CategoryRouter = require("./Sub_CategoryRoute/Sub_CategoryRoute");
const DepositRouter = require("./Sub_CategoryRoute/Sub_CategoryRoute");
const WithdrawRouter = require("./WithdrawRoute/WithdrawRoute");
const PaymentRouter = require("./PaymentRoute/PaymentRoute");
const ReviewRouter = require("./ReviewRoute/ReviewRoute");
// const ExpertsRouter = require("./ExpertsRoute/ExpertsRoute");
// const ClientsRouter = require("./ExpertsRoute/ExpertsRoute");
const AdminRouter = require("./AdminRoute/AdminRoute");
const ServiceRouter = require("./ServiceRoute/ServiceRoute");
const SettingsRouter = require("./SettingsRoute/SettingsRoute");
const TagRouter = require("./TagRoute/TagRoute");

router.use("/user", UserRouter);
router.use("/admin", AdminRouter);
// router.use("/experts", ExpertsRouter);
// router.use("/clients", ClientsRouter);
router.use("/job", JobRouter);
router.use("/service", ServiceRouter);
router.use("/category", CategoryRouter);
router.use("/sub-category", Sub_CategoryRouter);
router.use("/deposit", DepositRouter);
router.use("/withdraw", WithdrawRouter);
router.use("/payment", PaymentRouter);
router.use("/review", ReviewRouter);
router.use("/tag", TagRouter);
router.use("/settings", SettingsRouter);

module.exports = router;
